### ISSUE TITLE
[BUG] Bot doesn't know what LSST, Rubin and VRO is

### ISSUE THREAD

**Issue by steveschulze** [jeipollack/SlackGlossaryBot#6]
Hi,

I did 

/glossary acronym lsst
/glossary acronym LSST
/glossary acronym VRO
/glossary terms Rubin
/glossary terms lsst
/glossary terms LSST

The bot always returns that neither of these terms has a record.

Cheers,

Steve

**Comment by steveschulze** [comment]
Fixed. It was a user error.

**Comment by jeipollack** [comment]
Hi @steveschulze,
   thanks for opening an issue and noting you solved the problem. just to clarify the [DM glossary files](https://github.com/lsst/lsst-texmf/blob/main/etc/glossarydefs.csv) not only include acronyms/abbreviations but also compound words that can be queried, e.g. `/glossary prompt data product`.
